// Generated by https://quicktype.io
export interface BillAddressInterface {
  firstname: string;
  lastname: string;
  company?: string;
  address1: string;
  address2?: string;
  city: string;
  phone: string;
  zipcode?: string;
  state_name: string;
  country_iso?: string;
  label?: string;
}
