// Generated by https://quicktype.io
export interface CartData {
  data: CartInterface;
  included: Array;
}
export interface CartInterface {
  number: string;
  item_total: string;
  total: string;
  ship_total: string;
  adjustment_total: string;
  created_at: string;
  updated_at: string;
  completed_at: null;
  included_tax_total: string;
  additional_tax_total: string;
  display_additional_tax_total: string;
  display_included_tax_total: string;
  tax_total: string;
  currency: string;
  state: string;
  token: string;
  email: null;
  display_item_total: string;
  display_ship_total: string;
  display_adjustment_total: string;
  display_tax_total: string;
  promo_total: string;
  display_promo_total: string;
  item_count: number;
  special_instructions: null;
  display_total: string;
  pre_tax_item_amount: string;
  display_pre_tax_item_amount: string;
  pre_tax_total: string;
  display_pre_tax_total: string;
  shipment_state: null;
  payment_state: null;
  public_metadata: PublicMetadata;
}

export interface PublicMetadata {}
