// Generated by https://quicktype.io

export interface ShippingRateData {
  id: string;
  type: string;
  attributes: ShippingRateAttributes;
}
export interface ShipmentAttributes {
  number: string;
  final_price: string;
  display_final_price: string;
  state: string;
  shipped_at: null;
  tracking_url: null;
  free: boolean;
}

export interface ShippingRateAttributes {
  name: string;
  selected?: boolean;
  final_price?: string;
  display_final_price?: string;
  cost?: string;
  display_cost?: string;
  tax_amount?: string;
  display_tax_amount?: string;
  shipping_method_id: number;
  free?: boolean;
  quantity?: number;
  price?: string;
  slug?: string;
  options_text?: string;
  currency?: string;
  display_price?: string;
  total?: string;
  display_total?: string;
  adjustment_total?: string;
  display_adjustment_total?: string;
  additional_tax_total?: string;
  discounted_amount?: string;
  display_discounted_amount?: string;
  display_additional_tax_total?: string;
  promo_total?: string;
  display_promo_total?: string;
  included_tax_total?: string;
  display_included_tax_total?: string;
  pre_tax_amount?: string;
  display_pre_tax_amount?: string;
}
